# Generated by Django 3.2.6 on 2023-04-27 12:57

import botano.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=botano.models.upload_image_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('season', models.CharField(blank=True, max_length=200, null=True)),
                ('local_areas', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
